version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: always
    depends_on:
      - mongo
    env_file: .env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - net
  mongo: # user and db were not built yet
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - net

networks:
  net:

volumes:
  mongo:
